name: Build Firefox Add-on

on:
  issue_comment:
    types: [created, edited]


jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event.repository.owner.login == github.actor
      &&
      github.event.comment.body == '/build firefox'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build

    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: disengaged-${{ github.sha }}
        path: ${{ steps.web-ext-build.outputs.target }}