name: Build Firefox Add-on

on:
  repository_dispatch:
    types: [build-command]

env:
  SHA_TO_BUILD: ${{ github.event.client_payload.pull_request.head.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.login == github.actor

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.SHA_TO_BUILD }}

    - name: Build
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build

    - name: Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: disengaged-${{ env.SHA_TO_BUILD }}
        path: ${{ steps.web-ext-build.outputs.target }}